title: Carlos Braschi 
logo: 
description:
I am an Animal Scientist learning <br><br>
Data Analytics
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
